---
title: "Data Cleaning"
author: "Chenxi Huang (ch3129)"
date: "December 2, 2016"
output: html_document
---

```{r}
# set the working directory
setwd("C:/Users/celia/Desktop/Project 5")
set.seed(2016)
```

```{r}
# Load libraries
library(data.table)
library(dplyr)
library(base)
library(ggplot2)
#library(tidyr)


```

```{r}
# load data
load("./data/san.test.ori.Rdata")
subject()
san.test
dim(san.test)
# 929615  by   24
san.test.samp = san.test
dim(san.test.samp) # 929615  by  24

san.test.samp.name=names(san.test.samp)
# total features
san.test.samp.feat=names(san.test.samp)[1:24]
# total products
san.test.samp.label=names(san.test.samp)[25:48]

str(san.test.samp)
summary(san.test.samp[1:24,])
san.test.samp=as.data.frame(san.test.samp)

# save the data frame to compare later
san.dt=san.test.samp

```




```{r}
########## replace 1.0 to 1 ############
table(san.test.samp$indrel_1mes)
p.ind=which(san.test.samp$indrel_1mes == "P")
indrel.mis.ind=which(san.test.samp$indrel_1mes == "")
san.test.samp$indrel_1mes[p.ind] = 101
san.test.samp$indrel_1mes[indrel.mis.ind] = 200
table(san.test.samp$indrel_1mes)
san.test.samp$indrel_1mes = as.integer(san.test.samp$indrel_1mes)
table(san.test.samp$indrel_1mes)
san.test.samp$indrel_1mes[p.ind] = "P"
san.test.samp$indrel_1mes[indrel.mis.ind] = "unknown"
table(san.test.samp$indrel_1mes)



###### string missing values ########
which(san.test == "")
str.mis.ind_1=which(san.test.samp$fecha_dato == "")
san.test.samp$fecha_dato[str.mis.ind_1] = "unknown"

str.mis.ind_2=which(san.test.samp$ind_empleado  == "")
san.test.samp$ind_empleado[str.mis.ind_2] = "unknown"

str.mis.ind_3=which(san.test.samp$pais_residencia == "")
san.test.samp$pais_residencia[str.mis.ind_3] = "unknown"

str.mis.ind_4=which(san.test.samp$sexo == "")
san.test.samp$sexo[str.mis.ind_4] = "unknown"

str.mis.ind_5=which(san.test.samp$fecha_alta == "")
san.test.samp$fecha_alta[str.mis.ind_5] = "unknown"

str.mis.ind_6=which(san.test.samp$ult_fec_cli_1t == "")
san.test.samp$ult_fec_cli_1t[str.mis.ind_6] = "unknown"

str.mis.ind_7=which(san.test.samp$indrel_1mes == "")
san.test.samp$indrel_1mes[str.mis.ind_7] = "unknown"

str.mis.ind_8=which(san.test.samp$tiprel_1mes == "")
san.test.samp$tiprel_1mes[str.mis.ind_8] = "unknown"

str.mis.ind_9=which(san.test.samp$indresi == "")
san.test.samp$indresi[str.mis.ind_9] = "unknown"

str.mis.ind_10=which(san.test.samp$indext == "")
san.test.samp$indext[str.mis.ind_10] = "unknown"

str.mis.ind_11=which(san.test.samp$conyuemp == "")
san.test.samp$conyuemp[str.mis.ind_11] = "unknown"

str.mis.ind_12=which(san.test.samp$canal_entrada == "")
san.test.samp$canal_entrada[str.mis.ind_12] = "unknown"

str.mis.ind_13=which(san.test.samp$indfall == "")
san.test.samp$indfall[str.mis.ind_13] = "unknown"

str.mis.ind_14=which(san.test.samp$nomprov == "")
san.test.samp$nomprov[str.mis.ind_14] = "unknown"

str.mis.ind_15=which(san.test.samp$segmento == "")
san.test.samp$segmento[str.mis.ind_15] = "unknown"

which(san.test.samp == "")


####### Factorize the Strings ########
san.test.samp$fecha_dato = factor(san.test.samp$fecha_dato)
san.test.samp$ind_empleado  = factor(san.test.samp$ind_empleado)
san.test.samp$pais_residencia  = factor(san.test.samp$pais_residencia)
san.test.samp$sexo = factor(san.test.samp$sexo)
san.test.samp$fecha_alta = factor(san.test.samp$fecha_alta)
san.test.samp$ult_fec_cli_1t  = factor(san.test.samp$ult_fec_cli_1t)
san.test.samp$indrel_1mes  = factor(san.test.samp$indrel_1mes)
san.test.samp$tiprel_1mes  = factor(san.test.samp$tiprel_1mes)
san.test.samp$indresi  = factor(san.test.samp$indresi)
san.test.samp$indext  = factor(san.test.samp$indext)
san.test.samp$conyuemp  = factor(san.test.samp$conyuemp)
san.test.samp$canal_entrada  = factor(san.test.samp$canal_entrada)
san.test.samp$indfall  = factor(san.test.samp$indfall)
san.test.samp$nomprov  = factor(san.test.samp$nomprov)
san.test.samp$segmento = factor(san.test.samp$segmento)

str(san.test.samp)
``` 


```{r}
##################### Data Cleaning #####################

##### Time: Convert String to Time Format for calculation later ############
dato.mis.ind=which(san.test.samp$fecha_dato == "unknown")
alta.mis.ind=which(san.test.samp$fecha_alta == "unknown")
length(dato.mis.ind)
length(alta.mis.ind)

#t1=Sys.time()
san.test.samp$fecha_dato=as.POSIXct(strptime(san.test.samp$fecha_dato,format="%Y-%m-%d"))
#san.test.samp$fecha_alta=as.POSIXct(strptime(san.test.samp$fecha_alta,format="%Y-%m-%d"))
#t2=Sys.time()
#t2-t1
# check the dates in standard Year-Month-Day format
unique(san.test.samp$fecha_dato)
class(san.test.samp$fecha_dato)

# back to unknown
#san.test.samp$fecha_dato[dato.mis.ind] = "unknown"
#san.test.samp$fecha_alta[alta.mis.ind] = "unknown"
table(san.test.samp$fecha_alta)

# Are buying new product associated with Month?
# Add one more column of feature to original 
#san.test.samp$month=month(san.test.samp$fecha_dato)
#unique(san.test.samp$month)
#table(san.test.samp$month)
#plot(table(san.test.samp$month),xlab="month",ylab="frequency",main="Month Vs Frequency in Sampled Data")
# save plot
#dev.copy(png,'month.png')
#dev.off()
```


```{r}
# get some summary data first

summa.dato.y=summary(year(san.test.samp$fecha_dato))
summa.dato.y.table=table(year(san.test.samp$fecha_dato))
summa.dato.m=summary(month(san.test.samp$fecha_dato))
summa.dato.m.table=table(month(san.test.samp$fecha_dato))
year2015.ind=which(year(san.test.samp$fecha_dato)==2015)
year2016.ind=which(year(san.test.samp$fecha_dato)==2016)


summa.empleado=summary(factor(san.test.samp$ind_empleado))
table.empleado=table(factor(san.test.samp$ind_empleado))
empleado.A.ind=which(san.test.samp$ind_empleado=="A")
empleado.B.ind=which(san.test.samp$ind_empleado=="B")
empleado.F.ind=which(san.test.samp$ind_empleado=="F")
empleado.N.ind=which(san.test.samp$ind_empleado=="N")
empleado.P.ind=which(san.test.samp$ind_empleado=="P")
empleado.A.ind;length(empleado.A.ind) #232
empleado.B.ind;length(empleado.B.ind) #341
empleado.F.ind;length(empleado.F.ind) #209
empleado.N.ind;length(empleado.N.ind) # 11422931
empleado.P.ind;length(empleado.P.ind) #0


summa.pais=summary(factor(san.test.samp$pais_residencia))
summa.sexo=summary(factor(san.test.samp$sexo))
summa.alta=summary(san.test.samp$fecha_alta)
summa.ult_fec_cli_1t=summary(factor(san.test.samp$ult_fec_cli_1t))
summa.indrel_1mes=summary(factor(san.test.samp$indrel_1mes))
summa.tiprel_1mes=summary(factor(san.test.samp$tiprel_1mes))
summa.indresi=summary(factor(san.test.samp$indresi))
summa.indext=summary(factor(san.test.samp$indext))
summa.conyuemp=summary(factor(san.test.samp$conyuemp))
summa.canal_entrada=summary(factor(san.test.samp$canal_entrada))
summa.indfall=summary(factor(san.test.samp$indfall))        
summa.segmento=summary(factor(san.test.samp$segmento))
 
table.pais=table(factor(san.test.samp$pais_residencia))
table.sexo=table(factor(san.test.samp$sexo))
table.alta=table(san.test.samp$fecha_alta)
table.ult_fec_cli_1t=table(factor(san.test.samp$ult_fec_cli_1t))
table.indrel_1mes=table(factor(san.test.samp$indrel_1mes))
table.tiprel_1mes=table(factor(san.test.samp$tiprel_1mes))
table.indresi=table(factor(san.test.samp$indresi))
table.indext=table(factor(san.test.samp$indext))
table.conyuemp=table(factor(san.test.samp$conyuemp))
table.canal_entrada=table(factor(san.test.samp$canal_entrada))
table.indfall=table(factor(san.test.samp$indfall))        
table.segmento=table(factor(san.test.samp$segmento))                            
table.nomprove = table(san.test.samp$nomprov)

# looping to create summary tables for each feature
#list.table=list()
# for (k in length(names(san.test.samp))){
 #  list.table[[k]]=table(factor(san.test.samp$ind_empleado))}
 #list.table[[3]]

```


```{r}
############## Missing Values ################
# which columns have missing values?
ind.mis=which(sapply(san.test.samp,function(x) any(is.na(x))) == TRUE)
ind.mis
mis.name=names(san.test.samp)[ind.mis]
mis.name
#"indrel_1mes" "cod_prov"    "renta"    
length(mis.name) 
# 3 columns have missing values
```

```{r}
########### Missing Values: Age ##############
length(which(is.na(san.test.samp$age) == T))
# plot to see the distribution
age.table1=table(san.test.samp$age)
age.table1
plot(age.table1,main="Age Distribution_Test", xlab="Age",ylab="Frequency")
abline(h=1146,col="red")
# save plot
dev.copy(png,'age(ori.test).png')
dev.off()

# we can see that it peaked around age 19-24 and middle-aged people
# remove people with almost impossible ages
# age < 18 not many have bank accounts
# age > 90 too old 

summary(is.na(san.test.samp$age))   #all FALSE, no NA anymore
# done with age
```


```{r}
############################ 1. Missing Values: "indrel_1mes"########################
mis.name[5]
# "indrel"
# Customer type at the beginning of the month ,1 (First/Primary customer), 2 (co-owner ),P (Potential),3 (former primary), 4(former co-owner)

sum(is.na(san.test.samp$indrel_1mes)) 
# only 23 NAs
table(san.test.samp$indrel_1mes)
# fill with most common status: 1
san.test.samp$indrel_1mes[is.na(san.test.samp$indrel_1mes)]=1
sum(is.na(san.test.samp$indrel_1mes)) #0
# done here
```



```{r}
############################ 2. Missing Values: "cod_prov"########################
mis.name[1]
# cod_prov
# Province code (customer's address)
sum(is.na(san.test.samp$cod_prov)) #3806
cod_prov.ind=which(is.na(san.test.samp$cod_prov))

table(san.test.samp$cod_prov)  # balanced, no extreme cases
plot(table(san.test.samp$cod_prov))
# look at their province name
table(san.test.samp[is.na(san.test.samp$cod_prov),]$nomprov)
# same people
table(san.test.samp[is.na(san.test.samp$cod_prov),]$ncodpers)
san.test.samp[san.test.samp$ncodpers==208572,]

plot(table(san.test.samp$nomprov),xlab="province",ylab="frequency",main="Code Province Frequency_Test")
# save plot
dev.copy(png,'cod_prov_test.png')
dev.off()

which.max(table(san.test.samp$cod_prov))
# 28
# see which province is this 
san.test.samp[san.test.samp$cod_prov==28,]$nomprov
# MADRID
which.max(table(san.test.samp$nomprov))
# MADRID 32
# significantly more than other cities
# assign these prov codes to MARID
san.test.samp$cod_prov[is.na(san.test.samp$cod_prov)]=which.max(table(san.test.samp$cod_prov))
sum(is.na(san.test.samp$cod_prov)) #0


#san.test.samp$nomprov[which(san.test.samp$nomprov=="")]= "MADRID"
#sum(san.test.samp$nomprov == "") #0

```


```{r}
############################ 3. Missing Values: "renta" ########################
mis.name[3]
# renta
# Gross income of the household

sum(is.na(san.test.samp$renta)) #290984
# a lot of values are missing
income.table=table(san.test.samp$renta)
plot(income.table)


# could it be related to regions?

# region vs median of income 
plot.med=san.test.samp %>%
  filter(!is.na(renta)) %>%
  group_by(nomprov) %>%
  summarise(income.med = median(renta)) %>%
  arrange(income.med) %>%
  mutate(city=factor(nomprov,levels=nomprov)) %>% 
  ggplot(aes(x=city,y=income.med)) + 
  geom_point(color="sky blue") + 
  guides(color=FALSE) + 
  xlab("City") +
  ylab("Median of Income") +  
  theme(axis.text.x=element_blank(), axis.ticks = element_blank()) + 
  geom_text(aes(x=city,y=income.med,label=city),angle=90,hjust=-0.5) +
  ggtitle("Regional Income Distribution (By Median)_Test")
  
#region vs mean of income
plot.mean=san.test.samp %>%
  filter(!is.na(renta)) %>%
  group_by(nomprov) %>%
  summarise(income.mean = mean(renta)) %>%
  arrange(income.mean) %>%
  mutate(city=factor(nomprov,levels=nomprov)) %>% 
  ggplot(aes(x=city,y=income.mean)) + 
  geom_point(color="pink") + 
  guides(color=FALSE) + 
  xlab("City") +
  ylab("Mean of Income") +  
  theme(axis.text.x=element_blank(), axis.ticks = element_blank()) + 
  geom_text(aes(x=city,y=income.mean,label=city),angle=90,hjust=-0.5) +
  ggtitle("Regional Income Distribution (By Mean)_Test")


plot.med
# save plot
dev.copy(png,'income by median_test.png', height=600, width=1000)
dev.off()

plot.mean
# save plot
dev.copy(png,'income by mean_test.png', height=600, width=1000)
dev.off()


# choose median because it doesnt count extreme values
# see levels
city.level=unique(san.test.samp$nomprov)
city.n=length(unique(san.test.samp$nomprov)) # 53
city.n


# looping to get city income median
city.income.med=vector()
for (i in 1:city.n) {
  this_city=city.level[i]
  this_city.mat=san.test.samp[san.test.samp$nomprov==this_city,]
  this_city.na=which(is.na(this_city.mat$renta))
  this_city.clean=this_city.mat[-this_city.na,]
  this_city.med=median(this_city.clean$renta)
  city.income.med[i] = this_city.med
}

city.income.med
city.income=cbind(city.level,city.income.med)
city.income
dim(city.income)

# assign NA values by cities
ind.income.na=which(is.na(san.test.samp$renta))
ind.income.na

# looping
#t1=Sys.time()
#for (j in 1:length(ind.income.na)){
 # city_ind=ind.income.na[j]
  #the_city=san.test.samp$nomprov[city_ind]
  #the_city_income.ind=which(city.income[,1]==the_city)
  #the_city_income=as.numeric(city.income[the_city_income.ind,2])
  # assign values to NA
  #san.test.samp$renta[city_ind]=the_city_income}

#t2=Sys.time()
#t2 - t1
# san.test.samp$renta[5] = 66541.89
# this method takes too long

t1=Sys.time()
for(j in 1:city.n){
city_ind=which(san.test.samp$nomprov==city.level[j])
na.ind=which(is.na(san.test.samp[city_ind,]$renta)== T)

# assign values
san.test.samp[city_ind,][na.ind,]$renta = as.numeric(city.income[j,2])

}
t2=Sys.time()
t2 - t1
# Time difference of 19.66282 secs

san.test.samp$renta
san.test.samp$renta[5]
sum(is.na(san.test.samp$renta)) #0
# done
```



```{r}
# check summary of statistics to see what's wrong
df=san.test.samp
dt=san.test.samp

df_summa.dato.y=summary(year(df$fecha_dato))
df_table.dato.y=table(year(df$fecha_dato))
df_summa.dato.m=summary(month(df$fecha_dato))
df_table.dato.m=table(month(df$fecha_dato))
df.year2015.ind=which(year(df$fecha_dato)==2015)
df.year2016.ind=which(year(df$fecha_dato)==2016)


df_summa.empleado=summary(factor(df$ind_empleado))
df_table.empleado=table(factor(df$ind_empleado))
df_empleado.A.ind=which(df$ind_empleado=="A")
df_empleado.B.ind=which(df$ind_empleado=="B")
df_empleado.F.ind=which(df$ind_empleado=="F")
df_empleado.N.ind=which(df$ind_empleado=="N")
df_empleado.P.ind=which(df$ind_empleado=="P")
df_empleado.A.ind;length(empleado.A.ind) #232
df_empleado.B.ind;length(empleado.B.ind) #341
df_empleado.F.ind;length(empleado.F.ind) #209
df_empleado.N.ind;length(empleado.N.ind) # 1422931
df_empleado.P.ind;length(empleado.P.ind) #0


df_summa.pais=summary(factor(df$pais_residencia))
df_summa.sexo=summary(factor(df$sexo))
df_summa.alta=summary(df$fecha_alta)
df_summa.ult_fec_cli_1t=summary(factor(df$ult_fec_cli_1t))
df_summa.indrel_1mes=summary(factor(df$indrel_1mes))
df_summa.tiprel_1mes=summary(factor(df$tiprel_1mes))
df_summa.indresi=summary(factor(df$indresi))
df_summa.indext=summary(factor(df$indext))
df_summa.conyuemp=summary(factor(df$conyuemp))
df_summa.canal_entrada=summary(factor(df$canal_entrada))
df_summa.indfall=summary(factor(df$indfall))        
df_summa.segmento=summary(factor(df$segmento))
 
df_table.pais=table(factor(df$pais_residencia))
df_table.sexo=table(factor(df$sexo))
df_table.alta=table(df$fecha_alta)
df_table.ult_fec_cli_1t=table(factor(df$ult_fec_cli_1t))
df_table.indrel_1mes=table(factor(df$indrel_1mes))
df_table.tiprel_1mes=table(factor(df$tiprel_1mes))
df_table.indresi=table(factor(df$indresi))
df_table.indext=table(factor(df$indext))
df_table.conyuemp=table(factor(df$conyuemp))
df_table.canal_entrada=table(factor(df$canal_entrada))
df_table.indfall=table(factor(df$indfall))        
df_table.segmento=table(factor(df$segmento))      
df_table.nomprov=table(df$nomprov)

# check logicals 
summary(df_table.pais==table.pais)
summary(df_table.sexo==table.sexo)
summary(df_table.alta==table.alta)
summary(df_table.ult_fec_cli_1t==table.ult_fec_cli_1t)
summary(df_table.indrel_1mes==table.indrel_1mes)
summary(df_table.tiprel_1mes==table.tiprel_1mes)
summary(df_table.indresi==table.indresi)
summary(df_table.indext==table.indext)
summary(df_table.conyuemp==table.conyuemp)
summary(df_table.canal_entrada==table.canal_entrada)
summary(df_table.indfall==table.indfall)     
summary(df_table.segmento==table.segmento)
summary(df_table.nomprov==table.nomprove)
summary(df_table.empleado == table.empleado)

# all true. good!
# this means no string values has been changed.


```



```{r}
############## Feature Creation ############
############## New Feature 1: Month #############
# create a year_month column
names(df)

df$year_mon=sprintf("%s_%s",year(df$fecha_dato),month(df$fecha_dato))
df$year_mon 

table(factor(df$year_mon))
names(df)
str(df)

# check whether true
df$fecha_dato == san.dt$fecha_dato # true
df$pais_residencia == san.dt$pais_residencia # true
ind1=which(df$pais_residencia != san.dt$pais_residencia )
summary(ind1==str.mis.ind_3)


## create a month column 
### ** this is for the multinomial only. not for anyone else.

# Are buying new product associated with Month?
#Add one more column of feature to original 
dt$month=month(dt$fecha_dato)
unique(dt$month)
table(dt$month)

dt=cbind(dt[,c(1:24,49)],dt[,25:48])
names(dt)
str(dt)

# check whether true
dt$fecha_dato == san.dt$fecha_dato # true
dt$pais_residencia == san.dt$pais_residencia # true
ind2=which(dt$sexo != san.dt$sexo )
summary(ind2==str.mis.ind_4)

# convert dato back to factors
df$fecha_dato = factor(df$fecha_dato)
dt$fecha_dato = factor(dt$fecha_dato)
table(df$fecha_dato) == table(san.dt$fecha_dato) #true



str(df)
str(dt)
```


```{r}
# See if there is any missing values left
# which columns have missing values?
which(sapply(df,function(x) any(is.na(x))) == TRUE)
which(sapply(dt,function(x) any(is.na(x))) == TRUE)
#which(sapply(df,function(x) as.logical(x =="")) == TRUE)
which(df =="")
which(dt =="")
# all good
```


```{r}
# separate months and save in Rdata
table(factor(df$year_mon))

df.2015_1=filter(df,year_mon == "2015_1")
df.2015_2=filter(df,year_mon == "2015_2")
df.2015_3=filter(df,year_mon == "2015_3")
df.2015_4=filter(df,year_mon == "2015_4")
df.2015_5=filter(df,year_mon == "2015_5")
df.2015_6=filter(df,year_mon == "2015_6")
df.2015_7=filter(df,year_mon == "2015_7")
df.2015_8=filter(df,year_mon == "2015_8")
df.2015_9=filter(df,year_mon == "2015_9")
df.2015_10=filter(df,year_mon == "2015_10")
df.2015_11=filter(df,year_mon == "2015_11")
df.2015_12=filter(df,year_mon == "2015_12")
df.2016_1=filter(df,year_mon == "2016_1")
df.2016_2=filter(df,year_mon == "2016_2")
df.2016_3=filter(df,year_mon == "2016_3")
df.2016_4=filter(df,year_mon == "2016_4")
df.2016_5=filter(df,year_mon == "2016_5")
nrow(df.2015_1) == table(factor(df$year_mon))[1]
nrow(df.2015_2) == table(factor(df$year_mon))[5]
nrow(df.2015_3) == table(factor(df$year_mon))[6]
nrow(df.2015_4) == table(factor(df$year_mon))[7]
nrow(df.2015_5) == table(factor(df$year_mon))[8]
nrow(df.2015_6) == table(factor(df$year_mon))[9]
nrow(df.2015_7) == table(factor(df$year_mon))[10]
nrow(df.2015_8) == table(factor(df$year_mon))[11]
nrow(df.2015_9) == table(factor(df$year_mon))[12]
nrow(df.2015_10) == table(factor(df$year_mon))[2]
nrow(df.2015_11) == table(factor(df$year_mon))[3]
nrow(df.2015_12) == table(factor(df$year_mon))[4]
nrow(df.2016_1) == table(factor(df$year_mon))[13]
nrow(df.2016_2) == table(factor(df$year_mon))[14]
nrow(df.2016_3) == table(factor(df$year_mon))[15]
nrow(df.2016_4) == table(factor(df$year_mon))[16]
nrow(df.2016_5) == table(factor(df$year_mon))[17]

```


```{r}
# save Rdata
save(df,file = "df(final_test).RData")
save(dt,file = "dt(other_test).RData")

save(df.2015_1,file="df.2015_1_test.Rdata")
save(df.2015_2,file="df.2015_2_test.Rdata")
save(df.2015_3,file="df.2015_3_test.Rdata")
save(df.2015_4,file="df.2015_4_test.Rdata")
save(df.2015_5,file="df.2015_5_test.Rdata")
save(df.2015_6,file="df.2015_6_test.Rdata")
save(df.2015_7,file="df.2015_7_test.Rdata")
save(df.2015_8,file="df.2015_8_test.Rdata")
save(df.2015_9,file="df.2015_9_test.Rdata")
save(df.2015_10,file="df.2015_10_test.Rdata")
save(df.2015_11,file="df.2015_11_test.Rdata")
save(df.2015_12,file="df.2015_12_test.Rdata")
save(df.2016_1,file="df.2016_1_test.Rdata")
save(df.2016_2,file="df.2016_2_test.Rdata")
save(df.2016_3,file="df.2016_3_test.Rdata")
save(df.2016_4,file="df.2016_4_test.Rdata")
save(df.2016_5,file="df.2016_5_test.Rdata")
```
