---
title: "Data Cleaning"
author: "Chenxi Huang (ch3129)"
date: "December 2, 2016"
output: html_document
---

```{r}
# set the working directory
setwd("C:/Users/celia/Desktop/Project 5")
set.seed(2016)
```

```{r}
# Load libraries
library(data.table)
library(dplyr)
library(base)
library(ggplot2)
#library(tidyr)


```

```{r}
# load data
load("./data/san.train.samp(ori feat(smaller)).Rdata")
san.train.samp
dim(san.train.samp) # 1426529 by 48

san.train.samp.name=names(san.train.samp)
# total features
san.train.samp.feat=names(san.train.samp)[1:24]
# total products
san.train.samp.label=names(san.train.samp)[25:48]

str(san.train.samp)
summary(san.train.samp[1:24,])

```

```{r}
##################### Data Cleaning #####################

##### Time: Convert String to Time Format for calculation later ############
t1=Sys.time()
san.train.samp$fecha_dato=as.POSIXct(strptime(san.train.samp$fecha_dato,format="%Y-%m-%d"))
san.train.samp$fecha_alta=as.POSIXct(strptime(san.train.samp$fecha_alta,format="%Y-%m-%d"))
t2=Sys.time()
t2-t1
# check the dates in standard Year-Month-Day format
unique(san.train.samp$fecha_dato)
class(san.train.samp$fecha_dato)

# save the data frame to compare later
san.dt=san.train.samp

# Are buying new product associated with Month?
# Add one more column of feature to original 
#san.train.samp$month=month(san.train.samp$fecha_dato)
#unique(san.train.samp$month)
#table(san.train.samp$month)
#plot(table(san.train.samp$month),xlab="month",ylab="frequency",main="Month Vs Frequency in Sampled Data")
# save plot
#dev.copy(png,'month.png')
#dev.off()
```

```{r}
# get some summary data first

summa.dato.y=summary(year(san.train.samp$fecha_dato))
summa.dato.y.table=table(year(san.train.samp$fecha_dato))
summa.dato.m=summary(month(san.train.samp$fecha_dato))
summa.dato.m.table=table(month(san.train.samp$fecha_dato))
year2015.ind=which(year(san.train.samp$fecha_dato)==2015)
year2016.ind=which(year(san.train.samp$fecha_dato)==2016)


summa.empleado=summary(factor(san.train.samp$ind_empleado))
table.empleado=table(factor(san.train.samp$ind_empleado))
empleado.A.ind=which(san.train.samp$ind_empleado=="A")
empleado.B.ind=which(san.train.samp$ind_empleado=="B")
empleado.F.ind=which(san.train.samp$ind_empleado=="F")
empleado.N.ind=which(san.train.samp$ind_empleado=="N")
empleado.P.ind=which(san.train.samp$ind_empleado=="P")
empleado.A.ind;length(empleado.A.ind) #232
empleado.B.ind;length(empleado.B.ind) #341
empleado.F.ind;length(empleado.F.ind) #209
empleado.N.ind;length(empleado.N.ind) # 11422931
empleado.P.ind;length(empleado.P.ind) #0


summa.pais=summary(factor(san.train.samp$pais_residencia))
summa.sexo=summary(factor(san.train.samp$sexo))
summa.alta=summary(year(san.train.samp$fecha_alta))
summa.ult_fec_cli_1t=summary(factor(san.train.samp$ult_fec_cli_1t))
summa.indrel_1mes=summary(factor(san.train.samp$indrel_1mes))
summa.tiprel_1mes=summary(factor(san.train.samp$tiprel_1mes))
summa.indresi=summary(factor(san.train.samp$indresi))
summa.indext=summary(factor(san.train.samp$indext))
summa.conyuemp=summary(factor(san.train.samp$conyuemp))
summa.canal_entrada=summary(factor(san.train.samp$canal_entrada))
summa.indfall=summary(factor(san.train.samp$indfall))        
summa.segmento=summary(factor(san.train.samp$segmento))
 
table.pais=table(factor(san.train.samp$pais_residencia))
table.sexo=table(factor(san.train.samp$sexo))
table.alta=table(year(san.train.samp$fecha_alta))
table.ult_fec_cli_1t=table(factor(san.train.samp$ult_fec_cli_1t))
table.indrel_1mes=table(factor(san.train.samp$indrel_1mes))
table.tiprel_1mes=table(factor(san.train.samp$tiprel_1mes))
table.indresi=table(factor(san.train.samp$indresi))
table.indext=table(factor(san.train.samp$indext))
table.conyuemp=table(factor(san.train.samp$conyuemp))
table.canal_entrada=table(factor(san.train.samp$canal_entrada))
table.indfall=table(factor(san.train.samp$indfall))        
table.segmento=table(factor(san.train.samp$segmento))                            


# looping to create summary tables for each feature
#list.table=list()
# for (k in length(names(san.train.samp))){
 #  list.table[[k]]=table(factor(san.train.samp$ind_empleado))}
 #list.table[[3]]

```


```{r}
############## Missing Values ################
# which columns have missing values?
ind.mis=which(sapply(san.train.samp,function(x) any(is.na(x))) == TRUE)
ind.mis
mis.name=names(san.train.samp)[ind.mis]
mis.name
#"age","fecha_alta","ind_nuevo","antiguedad","indrel","tipodom","cod_prov","ind_actividad_cliente","renta","ind_nomina_ult1","ind_nom_pens_ult1"   
length(mis.name) 
# 11 columns have missing values
```

```{r}
########### 1. Missing Values: Age ##############
length(which(is.na(san.train.samp$age) == T))
# plot to see the distribution
age.table1=table(san.train.samp$age)
age.table1
plot(age.table1,main="Age Distribution", xlab="Age",ylab="Frequency")
abline(h=1146,col="red")
# save plot
dev.copy(png,'age(ori).png')
dev.off()

# we can see that it peaked around age 19-24 and middle-aged people
# remove people with almost impossible ages
# age < 18 not many have bank accounts
# age > 90 too old 

# fill in the NA with mean
san.train.samp$age[is.na(san.train.samp$age)]=mean(san.train.samp$age[(san.train.samp$age >= 18)&(san.train.samp$age <=90)],na.rm=TRUE)
# mean is  40.05889
# round them up
san.train.samp$age=round(san.train.samp$age)
age.table2=table(san.train.samp$age)
age.table2
summary(is.na(san.train.samp$age))   #all FALSE, no NA anymore
# done with age
```


```{r}
############ 2. Missing Values: fecha_alta ############
# The date in which the customer became as the first holder of a contract in the bank
# assign Na to median
table(san.train.samp$fecha_alta)
san.train.samp$fecha_alta[is.na(san.train.samp$fecha_alta)]=median(san.train.samp$fecha_alta,na.rm=TRUE)
sum(is.na(san.train.samp$fecha_alta)) #0
# done here
```


```{r}
############ 3. Missing Values: ind_nuevo (New customer Index) ############
# "ind_nuevo": New customer Index. 1 if the customer registered in the last 6 months.
sum(is.na(san.train.samp$ind_nuevo))
# 2816 NA

# let's see whether they are new customers by determining how many months of record they have been active
months.active=san.train.samp[is.na(san.train.samp$ind_nuevo),] %>%
                  group_by(ncodpers) %>%
                  summarise(months.active=n()) %>%
                  select(months.active)
max(months.active)
# 6 
# means they are all new customers
# assign 1 to NA
san.train.samp$ind_nuevo[is.na(san.train.samp$ind_nuevo)]=1 
sum(is.na(san.train.samp$ind_nuevo)) #0, no NA anymore
table(san.train.samp$ind_nuevo)
#     0 (1339068 ) and 1(87461 )
```


```{r}
############ 4. Missing Values: "antiguedad" ############
# Customer seniority (in months)
sum(is.na(san.train.samp$antiguedad))
# 2816
# same number as in the "ind_nuevo"
# probably the same people
summary(san.train.samp[is.na(san.train.samp$antiguedad),]%>%select(ind_nuevo))
# double check
# yes they are the same people


table(san.train.samp$antiguedad)
# check their registered number of months
cus.6month = c( 
             which(year(san.train.samp$fecha_alta) == 2015 & month(san.train.samp$fecha_alta)== 12),
             which(year(san.train.samp$fecha_alta) == 2016 & month(san.train.samp$fecha_alta)== 1),
             which(year(san.train.samp$fecha_alta) == 2016 & month(san.train.samp$fecha_alta)== 2),
             which(year(san.train.samp$fecha_alta) == 2016 & month(san.train.samp$fecha_alta)== 3),
             which(year(san.train.samp$fecha_alta) == 2016 & month(san.train.samp$fecha_alta)== 4),
             which(year(san.train.samp$fecha_alta) == 2016 & month(san.train.samp$fecha_alta) == 5))

length(cus.6month) #13137
# roughly the numbe of people who have registered under 6 months
san.train.samp$antiguedad[is.na(san.train.samp$antiguedad)]=min(san.train.samp$antiguedad,na.rm=TRUE)
sum(is.na(san.train.samp$antiguedad)) #0
# done here

```

```{r}
############################ 5. Missing Values: "indrel"########################
mis.name[5]
# "indrel"
# 1 (First/Primary), 99 (Primary customer during the month but not at the end of the month)
table(san.train.samp$indrel)
# fill with most common status
san.train.samp$indrel[is.na(san.train.samp$indrel)]=1
sum(is.na(san.train.samp$indrel)) #0
# done here
```


```{r}
############################ 6. Missing Values: "tipodom"########################
mis.name[6]
# "tipodom"
# Addres type. 1, primary address 
table(san.train.samp$tipodom)
# all=1,primary
# fill with most common status, which is only 1
sum(is.na(san.train.samp$tipodom)) 
# 2816, we've seen this number
# same group of the new customers
san.train.samp$tipodom[is.na(san.train.samp$tipodom)]=1
sum(is.na(san.train.samp$tipodom)) #0
# done here
```

```{r}
############################ 7. Missing Values: "cod_prov"########################
mis.name[7]
# cod_prov
# Province code (customer's address)
sum(is.na(san.train.samp$cod_prov)) #9805
cod_prov.ind=which(is.na(san.train.samp$cod_prov))

table(san.train.samp$cod_prov)  # balanced, no extreme cases
plot(table(san.train.samp$cod_prov))
# look at their province name
table(san.train.samp[is.na(san.train.samp$cod_prov),]$nomprov)
# same people
table(san.train.samp[is.na(san.train.samp$cod_prov),]$ncodpers)
san.train.samp[san.train.samp$ncodpers==208572,]

plot(table(san.train.samp$nomprov),xlab="province",ylab="frequency",main="Code Province Frequency")
# save plot
dev.copy(png,'cod_prov.png')
dev.off()

which.max(table(san.train.samp$cod_prov))
# 28
# see which province is this 
san.train.samp[san.train.samp$cod_prov==28,]$nomprov
# MADRID
which.max(table(san.train.samp$nomprov))
# MADRID 32
# significantly more than other cities
# assign these prov codes to MARID
san.train.samp$cod_prov[is.na(san.train.samp$cod_prov)]=which.max(table(san.train.samp$cod_prov))
sum(is.na(san.train.samp$cod_prov)) #0


#san.train.samp$nomprov[which(san.train.samp$nomprov=="")]= "MADRID"
#sum(san.train.samp$nomprov == "") #0

```

```{r}
############################ 8. Missing Values: 'ind_actividad_cliente"########################
mis.name[8]
# ind_actividad_cliente
# Activity index (1, active customer; 0, inactive customer)
sum(is.na(san.train.samp$ind_actividad_cliente))
#  2816
# same number, same group of people

table(san.train.samp$ind_actividad_cliente)
san.train.samp$ind_actividad_cliente[is.na(san.train.samp$ind_actividad_cliente)]=median(san.train.samp$ind_actividad_cliente,na.rm=TRUE)
sum(is.na(san.train.samp$ind_actividad_cliente)) #0
# done here
```


```{r}
############################ 9. Missing Values: "renta" ########################
mis.name[9]
# renta
# Gross income of the household

sum(is.na(san.train.samp$renta)) #290984
# a lot of values are missing
income.table=table(san.train.samp$renta)
plot(income.table)


# could it be related to regions?

# region vs median of income 
plot.med=san.train.samp %>%
  filter(!is.na(renta)) %>%
  group_by(nomprov) %>%
  summarise(income.med = median(renta)) %>%
  arrange(income.med) %>%
  mutate(city=factor(nomprov,levels=nomprov)) %>% 
  ggplot(aes(x=city,y=income.med)) + 
  geom_point(color="sky blue") + 
  guides(color=FALSE) + 
  xlab("City") +
  ylab("Median of Income") +  
  theme(axis.text.x=element_blank(), axis.ticks = element_blank()) + 
  geom_text(aes(x=city,y=income.med,label=city),angle=90,hjust=-0.5) +
  ggtitle("Regional Income Distribution (By Median)")
  
#region vs mean of income
plot.mean=san.train.samp %>%
  filter(!is.na(renta)) %>%
  group_by(nomprov) %>%
  summarise(income.mean = mean(renta)) %>%
  arrange(income.mean) %>%
  mutate(city=factor(nomprov,levels=nomprov)) %>% 
  ggplot(aes(x=city,y=income.mean)) + 
  geom_point(color="pink") + 
  guides(color=FALSE) + 
  xlab("City") +
  ylab("Mean of Income") +  
  theme(axis.text.x=element_blank(), axis.ticks = element_blank()) + 
  geom_text(aes(x=city,y=income.mean,label=city),angle=90,hjust=-0.5) +
  ggtitle("Regional Income Distribution (By Mean)")


plot.med
# save plot
dev.copy(png,'income by median.png', height=600, width=1000)
dev.off()

plot.mean
# save plot
dev.copy(png,'income by mean.png', height=600, width=1000)
dev.off()


# choose median because it doesnt count extreme values
# see levels
city.level=unique(san.train.samp$nomprov)
city.n=length(unique(san.train.samp$nomprov)) # 53
city.n


# looping to get city income median
city.income.med=vector()
for (i in 1:city.n) {
  this_city=city.level[i]
  this_city.mat=san.train.samp[san.train.samp$nomprov==this_city,]
  this_city.na=which(is.na(this_city.mat$renta))
  this_city.clean=this_city.mat[-this_city.na,]
  this_city.med=median(this_city.clean$renta)
  city.income.med[i] = this_city.med
}

city.income.med
city.income=cbind(city.level,city.income.med)
city.income
dim(city.income)

# assign NA values by cities
ind.income.na=which(is.na(san.train.samp$renta))
ind.income.na

# looping
#t1=Sys.time()
#for (j in 1:length(ind.income.na)){
 # city_ind=ind.income.na[j]
  #the_city=san.train.samp$nomprov[city_ind]
  #the_city_income.ind=which(city.income[,1]==the_city)
  #the_city_income=as.numeric(city.income[the_city_income.ind,2])
  # assign values to NA
  #san.train.samp$renta[city_ind]=the_city_income}

#t2=Sys.time()
#t2 - t1
# san.train.samp$renta[5] = 66541.89
# this method takes too long

t1=Sys.time()
for(j in 1:city.n){
city_ind=which(san.train.samp$nomprov==city.level[j])
na.ind=which(is.na(san.train.samp[city_ind,]$renta)== T)

# assign values
san.train.samp[city_ind,][na.ind,]$renta = as.numeric(city.income[j,2])

}
t2=Sys.time()
t2 - t1
# Time difference of 19.66282 secs

san.train.samp$renta
san.train.samp$renta[5]
sum(is.na(san.train.samp$renta)) #0
# done
```


```{r}
############################ 10. Missing Values: "ind_nomina_ult1" ########################
mis.name[10]
#"ind_nomina_ult1"
ind_nomina.mis=which(is.na(san.train.samp$ind_nomina_ult1))
sum(is.na(san.train.samp$ind_nomina_ult1))
# 1609
# fill in missing values for products by looking at previous months
#san.train.samp[ 377559,]
#san.train.samp[san.train.samp$ncodpers== 716415,]
# but previous months are also NA
# just make them zero then
# luckily not a large group

table.nomia=table(san.train.samp$ind_nomina_ult1)
#     0 : 1 = 1347882 : 77038 
#san.train.samp[is.na(san.train.samp$ind_nomina_ult1)]=0
#warnings()

sum(is.na(san.train.samp$ind_nom_pens_ult1)) #1609
#summary(san.train.samp$ind_nom_pens_ult1)
table.pens=table(san.train.samp$ind_nom_pens_ult1)   
#   0  :     1  = 1341419  : 83501 
pen.na.ind=which(is.na(san.train.samp$ind_nom_pens_ult1))


####################### warnings ##############################3
######## changin NA to o will alter the values of other string variables. 
######### fix this by deleting the column first and then add another new column with the values desired


#### create values of new columns first ####

nomia.1.ind=which(san.train.samp$ind_nomina_ult1==1)
pens.1.ind=which(san.train.samp$ind_nom_pens_ult1==1)
nomia.vec=rep(0,length(san.train.samp$ind_nomina_ult1))
pens.vec=rep(0,length(san.train.samp$ind_nom_pens_ult1))
nomia.vec[nomia.1.ind]=1
pens.vec[pens.1.ind]=1
table(nomia.vec) == table.nomia
table(pens.vec) == table.pens

recibo.vec=san.train.samp$ind_recibo_ult1
# Na values converted to 0 value=1 unchanged.


####### deleting old columns
san.train.samp=as.data.frame(san.train.samp)
drops=c("ind_nomina_ult1","ind_nom_pens_ult1","ind_recibo_ult1")
san.train.samp=san.train.samp[ , !(names(san.train.samp) %in% drops)]
dim(san.train.samp) #1426529 by 45, 3 columns down
names(san.train.samp)


######## append new columns to where old columns are #########
san.train.samp.name

san.train.samp$ind_nomina_ult1 = nomia.vec
san.train.samp$ind_nom_pens_ult1 = pens.vec
san.train.samp$ind_recibo_ult1 = recibo.vec
  
dim(san.train.samp) #  1426529 by 48, back to original # of columns
# adjusting locations of columns
names(san.train.samp)
#san.train.samp=cbind(san.train.samp[,1:45],san.train.samp$ind_nomina_ult1,san.train.samp$ind_nom_pens_ult1,san.train.samp$ind_recibo_ult1)
names(san.train.samp) == san.train.samp.name
# all true


sum(is.na(san.train.samp$ind_nomina_ult1)) #0
#san.train.samp$ind_nomina_ult1[ind_nomina.mis]
sum(is.na(san.train.samp$ind_nom_pens_ult1)) #0
san.train.samp$ind_recibo_ult1 == san.dt$ind_recibo_ult1 #TRUE
san.train.samp$fecha_dato == san.dt$fecha_dato #TRUE

# done here

```
```{r}
############################ 11. Missing Values: "ind_nom_pens_ult1" ########################
mis.name[11]
# "ind_nom_pens_ult1"
# Pensions
#sum(is.na(san.train.samp$ind_nom_pens_ult1))
#summary(san.train.samp$ind_nom_pens_ult1)
#table(san.train.samp$ind_nom_pens_ult1)
#pen.na.ind=which(is.na(san.train.samp$ind_nom_pens_ult1))
#pen.na.ind

# 0
#? how so 
# before setting up payroll=0, it was 1609
#san.train.samp$ind_nom_pens_ult1[ind_nomina.mis]
#san.train.samp[is.na(san.train.samp$ind_nom_pens_ult1)]=0
#san.train.samp$ind_nom_pens_ult1[ind_nomina.mis]
# looks like ind_nomina_ult1 and ind_nom_pens_ult1 are dependent!!!
```

```{r}
################## Missing Values for Str ############
#empleado.mis.ind=which(san.train.samp$ind_empleado=="")
# assign values to the marjority
#san.train.samp$ind_empleado[empleado.mis.ind]="N"


# decided not to fill in "" of strings. let them be a group.

```


```{r}
# check summary of statistics to see what's wrong
df=san.train.samp
dt=san.train.samp

df_summa.dato.y=summary(year(df$fecha_dato))
df_table.dato.y=table(year(df$fecha_dato))
df_summa.dato.m=summary(month(df$fecha_dato))
df_table.dato.m=table(month(df$fecha_dato))
df.year2015.ind=which(year(df$fecha_dato)==2015)
df.year2016.ind=which(year(df$fecha_dato)==2016)


df_summa.empleado=summary(factor(df$ind_empleado))
df_table.empleado=table(factor(df$ind_empleado))
df_empleado.A.ind=which(df$ind_empleado=="A")
df_empleado.B.ind=which(df$ind_empleado=="B")
df_empleado.F.ind=which(df$ind_empleado=="F")
df_empleado.N.ind=which(df$ind_empleado=="N")
df_empleado.P.ind=which(df$ind_empleado=="P")
df_empleado.A.ind;length(empleado.A.ind) #232
df_empleado.B.ind;length(empleado.B.ind) #341
df_empleado.F.ind;length(empleado.F.ind) #209
df_empleado.N.ind;length(empleado.N.ind) # 1422931
df_empleado.P.ind;length(empleado.P.ind) #0


df_summa.pais=summary(factor(df$pais_residencia))
df_summa.sexo=summary(factor(df$sexo))
df_summa.alta=summary(year(df$fecha_alta))
df_summa.ult_fec_cli_1t=summary(factor(df$ult_fec_cli_1t))
df_summa.indrel_1mes=summary(factor(df$indrel_1mes))
df_summa.tiprel_1mes=summary(factor(df$tiprel_1mes))
df_summa.indresi=summary(factor(df$indresi))
df_summa.indext=summary(factor(df$indext))
df_summa.conyuemp=summary(factor(df$conyuemp))
df_summa.canal_entrada=summary(factor(df$canal_entrada))
df_summa.indfall=summary(factor(df$indfall))        
df_summa.segmento=summary(factor(df$segmento))
 
df_table.pais=table(factor(df$pais_residencia))
df_table.sexo=table(factor(df$sexo))
df_table.alta=table(year(df$fecha_alta))
df_table.ult_fec_cli_1t=table(factor(df$ult_fec_cli_1t))
df_table.indrel_1mes=table(factor(df$indrel_1mes))
df_table.tiprel_1mes=table(factor(df$tiprel_1mes))
df_table.indresi=table(factor(df$indresi))
df_table.indext=table(factor(df$indext))
df_table.conyuemp=table(factor(df$conyuemp))
df_table.canal_entrada=table(factor(df$canal_entrada))
df_table.indfall=table(factor(df$indfall))        
df_table.segmento=table(factor(df$segmento))      


# check logicals 
summary(df_table.pais==table.pais)
summary(df_table.sexo==table.sexo)
summary(df_table.alta==table.alta)
summary(df_table.ult_fec_cli_1t==table.ult_fec_cli_1t)
summary(df_table.indrel_1mes==table.indrel_1mes)
summary(df_table.tiprel_1mes==table.tiprel_1mes)
summary(df_table.indresi==table.indresi)
summary(df_table.indext==table.indext)
summary(df_table.conyuemp==table.conyuemp)
summary(df_table.canal_entrada==table.canal_entrada)
summary(df_table.indfall==table.indfall)     
summary(df_table.segmento==table.segmento)

# all true. good!
# this means no string values has been changed.

```



```{r}
############## Feature Creation ############
############## New Feature 1: Month #############
# create a year_month column
names(df)

df$year_mon=sprintf("%s_%s",year(df$fecha_dato),month(df$fecha_dato))
df$year_mon
table(factor(df$year_mon))
names(df)
str(df)

# check whether true
df$fecha_dato == san.dt$fecha_dato # true
df$pais_residencia == san.dt$pais_residencia # true



## create a month column 
### ** this is for the multinomial only. not for anyone else.

# Are buying new product associated with Month?
#Add one more column of feature to original 
dt$month=month(dt$fecha_dato)
unique(dt$month)
table(dt$month)

dt=cbind(dt[,c(1:24,49)],dt[,25:48])
names(dt)
str(dt)

# check whether true
df$fecha_dato == san.dt$fecha_dato # true
dt$pais_residencia == san.dt$pais_residencia # true

```


```{r}
# See if there is any missing values left
# which columns have missing values?
which(sapply(san.train.samp,function(x) any(is.na(x))) == TRUE)
# all good
```


```{r}
# separate months and save in Rdata
table(factor(df$year_mon))

df.2015_1=filter(df,year_mon == "2015_1")
df.2015_2=filter(df,year_mon == "2015_2")
df.2015_3=filter(df,year_mon == "2015_3")
df.2015_4=filter(df,year_mon == "2015_4")
df.2015_5=filter(df,year_mon == "2015_5")
df.2015_6=filter(df,year_mon == "2015_6")
df.2015_7=filter(df,year_mon == "2015_7")
df.2015_8=filter(df,year_mon == "2015_8")
df.2015_9=filter(df,year_mon == "2015_9")
df.2015_10=filter(df,year_mon == "2015_10")
df.2015_11=filter(df,year_mon == "2015_11")
df.2015_12=filter(df,year_mon == "2015_12")
df.2016_1=filter(df,year_mon == "2016_1")
df.2016_2=filter(df,year_mon == "2016_2")
df.2016_3=filter(df,year_mon == "2016_3")
df.2016_4=filter(df,year_mon == "2016_4")
df.2016_5=filter(df,year_mon == "2016_5")
nrow(df.2015_1) == table(factor(df$year_mon))[1]
nrow(df.2015_2) == table(factor(df$year_mon))[5]
nrow(df.2015_3) == table(factor(df$year_mon))[6]
nrow(df.2015_4) == table(factor(df$year_mon))[7]
nrow(df.2015_5) == table(factor(df$year_mon))[8]
nrow(df.2015_6) == table(factor(df$year_mon))[9]
nrow(df.2015_7) == table(factor(df$year_mon))[10]
nrow(df.2015_8) == table(factor(df$year_mon))[11]
nrow(df.2015_9) == table(factor(df$year_mon))[12]
nrow(df.2015_10) == table(factor(df$year_mon))[2]
nrow(df.2015_11) == table(factor(df$year_mon))[3]
nrow(df.2015_12) == table(factor(df$year_mon))[4]
nrow(df.2016_1) == table(factor(df$year_mon))[13]
nrow(df.2016_2) == table(factor(df$year_mon))[14]
nrow(df.2016_3) == table(factor(df$year_mon))[15]
nrow(df.2016_4) == table(factor(df$year_mon))[16]
nrow(df.2016_5) == table(factor(df$year_mon))[17]

```


```{r}
# save Rdata
save(df,file = "df(final).RData")
save(dt,file = "dt(other).RData")

save(df.2015_1,file="df.2015_1.Rdata")
save(df.2015_2,file="df.2015_2.Rdata")
save(df.2015_3,file="df.2015_3.Rdata")
save(df.2015_4,file="df.2015_4.Rdata")
save(df.2015_5,file="df.2015_5.Rdata")
save(df.2015_6,file="df.2015_6.Rdata")
save(df.2015_7,file="df.2015_7.Rdata")
save(df.2015_8,file="df.2015_8.Rdata")
save(df.2015_9,file="df.2015_9.Rdata")
save(df.2015_10,file="df.2015_10.Rdata")
save(df.2015_11,file="df.2015_11.Rdata")
save(df.2015_12,file="df.2015_12.Rdata")
save(df.2016_1,file="df.2016_1.Rdata")
save(df.2016_2,file="df.2016_2.Rdata")
save(df.2016_3,file="df.2016_3.Rdata")
save(df.2016_4,file="df.2016_4.Rdata")
save(df.2016_5,file="df.2016_5.Rdata")
```
