---
title: "proj5_rFerns_month"
author: "Chenxi Huang (ch3129)"
date: "December 7, 2016"
output: html_document
---

```{r}
setwd("C:/Users/celia/Desktop/Project 5")
```

```{r}
# install packages
#install.packages("rFerns")
#install.packages("mldr")
#install.packages("mlr")
#install.packages("gdata")
# install.packages("randomForestSRC")
```

```{r}
# load libraries
library(rFerns)
library(randomForestSRC)
# for multi-lable classification
library(mlr) #train masked
# need to use mlr::train
library(mldr)
# for explatory analysis of multi-label classification 
#library(cluster) # for gower similarity and pam
#library(Rtsne) # for t-SNE plot
library(ggplot2) # for visualization
library(gdata)
set.seed(111)
```

```{r}
# load data 
load("./df(final).Rdata")
dt=df
names(dt)
dim(dt)
# 1426529 by 49

# get rid of 
```

```{r}
#get data in the right format
# need a data.frame
class(dt)
# data frame

# include features and a logical vector for each label 
lab.col=dt[,25:48]
#labels=names(lab.col)
lab.mat=matrix(nrow=nrow(lab.col),ncol=ncol(lab.col))

# assign logical values
ind.10=which(lab.col$ind_ahor_fin_ult1 == 0)
ind.11=which(lab.col$ind_ahor_fin_ult1 == 1)
lab.mat[,1][ind.10] = F
lab.mat[,1][ind.11] = T

ind.20=which(lab.col$ind_aval_fin_ult1 == 0)
ind.21=which(lab.col$ind_aval_fin_ult1 == 1)
lab.mat[,2][ind.20]=F
lab.mat[,2][ind.21]=T

ind.30=which(lab.col$ind_cco_fin_ult1 == 0)
ind.31=which(lab.col$ind_cco_fin_ult1 == 1)
lab.mat[,3][ind.30]=F
lab.mat[,3][ind.31]=T

ind.40=which(lab.col$ind_cder_fin_ult1 == 0)
ind.41=which(lab.col$ind_cder_fin_ult1 == 1)
lab.mat[,4][ind.40]=F
lab.mat[,4][ind.41]=T

ind.50=which(lab.col$ind_cno_fin_ult1 == 0)
ind.51=which(lab.col$ind_cno_fin_ult1 == 1)
lab.mat[,5][ind.50]=F
lab.mat[,5][ind.51]=T

ind.60=which(lab.col$ind_ctju_fin_ult1 == 0)
ind.61=which(lab.col$ind_ctju_fin_ult1 == 1)
lab.mat[,6][ind.60]=F
lab.mat[,6][ind.61]=T

ind.70=which(lab.col$ind_ctma_fin_ult1 == 0)
ind.71=which(lab.col$ind_ctma_fin_ult1 == 1)
lab.mat[,7][ind.70]=F
lab.mat[,7][ind.71]=T

ind.80=which(lab.col$ind_ctop_fin_ult1 == 0)
ind.81=which(lab.col$ind_ctop_fin_ult1 == 1)
lab.mat[,8][ind.80]=F
lab.mat[,8][ind.81]=T

ind.90=which(lab.col$ind_ctpp_fin_ult1 == 0)
ind.91=which(lab.col$ind_ctpp_fin_ult1 == 1)
lab.mat[,9][ind.90]=F
lab.mat[,9][ind.91]=T

ind.100=which(lab.col$ind_deco_fin_ult1 == 0)
ind.101=which(lab.col$ind_deco_fin_ult1 == 1)
lab.mat[,10][ind.100]=F
lab.mat[,10][ind.101]=T

ind.110=which(lab.col$ind_deme_fin_ult1 == 0)
ind.111=which(lab.col$ind_deme_fin_ult1 == 1)
lab.mat[,11][ind.110]=F
lab.mat[,11][ind.111]=T

ind.120=which(lab.col$ind_dela_fin_ult1 == 0)
ind.121=which(lab.col$ind_dela_fin_ult1 == 1)
lab.mat[,12][ind.120]=F
lab.mat[,12][ind.121]=T

ind.130=which(lab.col$ind_ecue_fin_ult1 == 0)
ind.131=which(lab.col$ind_ecue_fin_ult1 == 1)
lab.mat[,13][ind.130]=F
lab.mat[,13][ind.131]=T

ind.140=which(lab.col$ind_fond_fin_ult1 == 0)
ind.141=which(lab.col$ind_fond_fin_ult1 == 1)
lab.mat[,14][ind.140]=F
lab.mat[,14][ind.141]=T

ind.150=which(lab.col$ind_hip_fin_ult1 == 0)
ind.151=which(lab.col$ind_hip_fin_ult1 == 1)
lab.mat[,15][ind.150]=F
lab.mat[,15][ind.151]=T

ind.160=which(lab.col$ind_plan_fin_ult1 == 0)
ind.161=which(lab.col$ind_plan_fin_ult1 == 1)
lab.mat[,16][ind.160]=F
lab.mat[,16][ind.161]=T

ind.170=which(lab.col$ind_pres_fin_ult1 == 0)
ind.171=which(lab.col$ind_pres_fin_ult1 == 1)
lab.mat[,17][ind.170]=F
lab.mat[,17][ind.171]=T

ind.180=which(lab.col$ind_reca_fin_ult1 == 0)
ind.181=which(lab.col$ind_reca_fin_ult1 == 1)
lab.mat[,18][ind.180]=F
lab.mat[,18][ind.181]=T

ind.190=which(lab.col$ind_tjcr_fin_ult1 == 0)
ind.191=which(lab.col$ind_tjcr_fin_ult1 == 1)
lab.mat[,19][ind.190]=F
lab.mat[,19][ind.191]=T

ind.200=which(lab.col$ind_valo_fin_ult1 == 0)
ind.201=which(lab.col$ind_valo_fin_ult1 == 1)
lab.mat[,20][ind.200]=F
lab.mat[,20][ind.201]=T

ind.210=which(lab.col$ind_viv_fin_ult1 == 0)
ind.211=which(lab.col$ind_viv_fin_ult1 == 1)
lab.mat[,21][ind.210]=F
lab.mat[,21][ind.211]=T

ind.220=which(lab.col$ind_nomina_ult1 == 0)
ind.221=which(lab.col$ind_nomina_ult1 == 1)
lab.mat[,22][ind.220]=F
lab.mat[,22][ind.221]=T

ind.230=which(lab.col$ind_nom_pens_ult1 == 0)
ind.231=which(lab.col$ind_nom_pens_ult1 == 1)
lab.mat[,23][ind.230]=F
lab.mat[,23][ind.231]=T

ind.240=which(lab.col$ind_recibo_ult1 == 0)
ind.241=which(lab.col$ind_recibo_ult1 == 1)
lab.mat[,24][ind.240]=F
lab.mat[,24][ind.241]=T

lab.mat
#san=cbind(lab.mat,dt[,1:25])


# 1426529 by 24
labels=c("label1","label2","label3","label4","label5","label6","label7","label8",
          "label9","label10","label11","label12","label13","label14","label15","label16",
          "label17","label18","label19","label20","label21","label22","label23","label24")

colnames(lab.mat) = labels
length(labels)

dim(lab.mat)
#labels = colnames(dt)[1:14]



san= cbind(dt[,1:24],lab.mat)
san[1,]
dim(san)
# san.new=cbind(dt[,1:25],lab.mat)
# dim(san.new)


# order factors with >30 levels
levels(san$pais_residencia)
table(san$pais_residencia)
san$pais_residencia = reorder(san$pais_residencia, X=as.numeric(san$pais_residencia), FUN=length)
levels(san$pais_residencia)
summary(san$pais_residencia)
san$pais_residencia=ordered(san$pais_residencia)
is.ordered(san$pais_residencia) #TRUE
summary(as.character(san$pais_residencia) == as.character(dt$pais_residencia)) #TRUE

levels(san$fecha_alta)
table(san$fecha_alta)
san$fecha_alta = reorder(san$fecha_alta, X=as.numeric(san$fecha_alta), FUN=length)
san$fecha_alta
levels(san$fecha_alta)
summary(san$fecha_alta)
san$fecha_alta=ordered(san$fecha_alta)
is.ordered(san$fecha_alta) #TRUE
summary(as.character(san$fecha_alta) == as.character(dt$fecha_alta)) #TRUE


levels(san$ult_fec_cli_1t)
table(san$ult_fec_cli_1t)
san$ult_fec_cli_1t = reorder(san$ult_fec_cli_1t, X=as.numeric(san$ult_fec_cli_1t), FUN=length)
levels(san$ult_fec_cli_1t)
summary(san$ult_fec_cli_1t)
san$ult_fec_cli_1t=ordered(san$ult_fec_cli_1t)
is.ordered(san$ult_fec_cli_1t) #TRUE
summary(as.character(san$ult_fec_cli_1t) == as.character(dt$ult_fec_cli_1t)) #TRUE


levels(san$canal_entrada)
table(san$canal_entrada)
san$canal_entrada = reorder(san$canal_entrada, X=as.numeric(san$canal_entrada), FUN=length)
levels(san$canal_entrada)
summary(san$canal_entrada)
san$canal_entrada=ordered(san$canal_entrada)
is.ordered(san$canal_entrada) #TRUE
summary(as.character(san$canal_entrada) == as.character(dt$canal_entrada)) #TRUE


levels(san$nomprov)
table(san$nomprov)
san$nomprov = reorder(san$nomprov, X=as.numeric(san$nomprov), FUN=length)
levels(san$nomprov)
summary(san$nomprov)
san$nomprov=ordered(san$nomprov)
is.ordered(san$nomprov) #TRUE
summary(as.character(san$nomprov) == as.character(dt$nomprov)) #TRUE


dim(san)


drop.level = c("fecha_dato","ind_empleado","pais_residencia","fecha_alta","ult_fec_cli_1t","tiprel_1mes","indresi","indext","canal_entrada","indfall")
drop.ind=match(drop.level, names(san))
san = san[, -drop.ind]
dim(san)
names(san)

april.ind=which(dt$year_mon == "2016_4")
san.april= cbind(san[april.ind,1:14],lab.mat[april.ind,])
dim(san.april)
san.april[1,]
#san.april = san.april[, -drop.ind]
dim(san.april)
#colnames(san.april[,15:38]) = labels


may.ind=which(dt$year_mon == "2016_5")
san.may= cbind(san[may.ind,1:14],lab.mat[may.ind,])
dim(san.may)
san.may[1,]
#san.may = san.may[, -drop.ind]
dim(san.may)


names(san.april)
dim(san.april)
dim(san.may)

which(san.april == "")


april.may = match(san.april$ncodpers,san.may$ncodpers)
san.april.NF = cbind(san.april,san.may[april.may,15:38])
names(san.april.NF)
dim(san.april.NF)
lab.current = c("label_cur1","label_cur2","label_cur3","label_cur4","label_cur5","label_cur6","label_cur7","label_cur8",
          "label_cur9","label_cur10","label_cur11","label_cur12","label_cur13","label_cur14","label_cur15","label_cur16",
          "label_cur17","label_cur18","label_cur19","label_cur20","label_cur21","label_cur22","label_cur23","label_cur24")
colnames(san.april.NF) = c(names(san.april)[1:14],lab.current,labels)
names(san.april.NF)
dim(san.april.NF)

san.april.NF <- ifelse(san.april.NF == TRUE, 1, 0)
san.april.NF = as.data.frame(san.april.NF)
fac.mat.april = san.april.NF[,15:38]
fac.mat.april[,1]= factor(fac.mat.april[,1])
fac.mat.april[,2]= factor(fac.mat.april[,2])
fac.mat.april[,3]= factor(fac.mat.april[,3])
fac.mat.april[,4]= factor(fac.mat.april[,4])
fac.mat.april[,5]= factor(fac.mat.april[,5])
fac.mat.april[,6]= factor(fac.mat.april[,6])
fac.mat.april[,7]= factor(fac.mat.april[,7])
fac.mat.april[,8]= factor(fac.mat.april[,8])
fac.mat.april[,9]= factor(fac.mat.april[,9])
fac.mat.april[,10]= factor(fac.mat.april[,10])
fac.mat.april[,11]= factor(fac.mat.april[,11])
fac.mat.april[,12]= factor(fac.mat.april[,12])
fac.mat.april[,13]= factor(fac.mat.april[,13])
fac.mat.april[,14]= factor(fac.mat.april[,14])
fac.mat.april[,15]= factor(fac.mat.april[,15])
fac.mat.april[,16]= factor(fac.mat.april[,16])
fac.mat.april[,17]= factor(fac.mat.april[,17])
fac.mat.april[,18]= factor(fac.mat.april[,18])
fac.mat.april[,19]= factor(fac.mat.april[,19])
fac.mat.april[,20]= factor(fac.mat.april[,20])
fac.mat.april[,21]= factor(fac.mat.april[,21])
fac.mat.april[,22]= factor(fac.mat.april[,22])
fac.mat.april[,23]= factor(fac.mat.april[,23])
fac.mat.april[,24]= factor(fac.mat.april[,24])

san.april.NF[,15:38] = fac.mat.april

str(san.april.NF)
san.april.NF[,39:62] = san.may[april.may,15:38]
dim(san.april.NF)
names(san.april.NF)
# 97105 by  62

san.may.NF = san.may[april.may,]
san.may.NF <- ifelse(san.may.NF == TRUE, 1, 0)
san.may.NF = as.data.frame(san.may.NF)
fac.mat.may = san.may.NF[,15:38]
fac.mat.may[,1]= factor(fac.mat.may[,1])
fac.mat.may[,2]= factor(fac.mat.may[,2])
fac.mat.may[,3]= factor(fac.mat.may[,3])
fac.mat.may[,4]= factor(fac.mat.may[,4])
fac.mat.may[,5]= factor(fac.mat.may[,5])
fac.mat.may[,6]= factor(fac.mat.may[,6])
fac.mat.may[,7]= factor(fac.mat.may[,7])
fac.mat.may[,8]= factor(fac.mat.may[,8])
fac.mat.may[,9]= factor(fac.mat.may[,9])
fac.mat.may[,10]= factor(fac.mat.may[,10])
fac.mat.may[,11]= factor(fac.mat.may[,11])
fac.mat.may[,12]= factor(fac.mat.may[,12])
fac.mat.may[,13]= factor(fac.mat.may[,13])
fac.mat.may[,14]= factor(fac.mat.may[,14])
fac.mat.may[,15]= factor(fac.mat.may[,15])
fac.mat.may[,16]= factor(fac.mat.may[,16])
fac.mat.may[,17]= factor(fac.mat.may[,17])
fac.mat.may[,18]= factor(fac.mat.may[,18])
fac.mat.may[,19]= factor(fac.mat.may[,19])
fac.mat.may[,20]= factor(fac.mat.may[,20])
fac.mat.may[,21]= factor(fac.mat.may[,21])
fac.mat.may[,22]= factor(fac.mat.may[,22])
fac.mat.may[,23]= factor(fac.mat.may[,23])
fac.mat.may[,24]= factor(fac.mat.may[,24])

san.may.NF[,15:38] = fac.mat.may

str(san.may.NF)
dim(san.may.NF)

# subtract the month column
#which(names(san)== "month") #25
#san = san[,-25]
#names(san);length(names(san)) #48
# create the task
san.task = makeMultilabelTask(id = "multi", data=san.april.NF, target=labels)
san.task




# data ready

#  Empty factor levels were dropped for columns: 
# ind_empleado,pais_residencia,fecha_alta,ult_fec_cli_1t,tiprel_1mes,indresi,indext,canal_entrada,indfall
```


```{r}
# Algorithm adaptation methods
san.ferns = makeLearner("multilabel.rFerns")
san.ferns

san.forest = makeLearner("multilabel.randomForestSRC")
san.forest


```

```{r}
# Training
# train a model as usual with a multilabel learner and a multilabel task as input. 
# can also pass subset and weights arguments if the learner supports this.
t1=Sys.time()
mod.ferns = mlr::train(learner=san.ferns, task=san.task)
mod.ferns
t2=Sys.time()
t2 - t1
#Time difference of 4.732218 mins

class(mod.ferns) #"WrappedModel"
# Model for learner.id=multilabel.rFerns; learner.class=multilabel.rFerns
#Trained on: task.id = multi; obs = 1426529; features = 25
#Hyperparameters: 


###### random forest #########
t1=Sys.time()
mod.forest = mlr::train(learner=san.forest, task=san.task)
mod.forest
t2=Sys.time()
t2 - t1
#Time difference of 58.95171 secs

class(mod.forest) #"WrappedModel"

```


```{r}
# Predicting

#load new data



# can be done as usual in mlr with predict 
pred1 = predict(mod.ferns, task = san.task, subset = 1:10)
t1 = sys.time()
pred2 = predict(mod.ferns, newdata = san.may.NF)
t2.sys.time()
t2 - t1
#pred3 = predict(mod.ferns, task = san.task, subset = 50000:10000)
names(as.data.frame(pred))

class(pred1)
#"PredictionMultilabel" "Prediction"         
pred.df=as.data.frame(pred1)
dim(pred.df) # 10 49
pred.lab=pred.df[,2:25]
pred.res=pred.df[,26:49]

correct.rate= length(which(pred.lab == pred.res))/(10*24)
correct.rate #0.9

summary(pred.lab == pred.res)
table(summary(pred.lab == pred.res))
```

```{r}
# Performance
#performance of prediction can be assessed via function performance
#can specify via the measures argument which measure(s) to calculate
#The default measure for multilabel classification is the Hamming loss (multilabel.hamloss)
performance(pred1)
# error rate is # 0.09166667 
# no month:  0.1 

performance(pred2)
# error rate is # 0.2338637 

performance(pred3)
# error rate is #  0.2746598 

performance(pred1, measures = list(multilabel.subset01, multilabel.hamloss, multilabel.acc,
                                multilabel.f1, timepredict))

listMeasures("multilabel")
```

```{r}
# Resampling
learner=san.ferns
task=san.task
#For evaluating the overall performance of the learning algorithm

rdesc = makeResampleDesc(method = "CV", stratify = FALSE, iters = 3)
r = mlr::resample(learner, task, resampling = rdesc, show.info = FALSE)
r


# iters=3
#Resample Results
#Task: multi
#Learner: multilabel.rFerns
#multilabel.hamloss.aggr: 0.24
#multilabel.hamloss.mean: 0.24
#multilabel.hamloss.sd: 0.00
#Runtime: 8.61958


# iters=5
#Resample Result
#Task: multi
#Learner: multilabel.rFerns
#multilabel.hamloss.aggr: 0.24
#multilabel.hamloss.mean: 0.24
#multilabel.hamloss.sd: 0.00
#Runtime: 15.4731


# without month
#Resample Result
#Task: multi
#Learner: multilabel.rFerns
#multilabel.hamloss.aggr: 0.24
#multilabel.hamloss.mean: 0.24
#multilabel.hamloss.sd: 0.00
#Runtime: 8.44528

class(r)
dim(r)

```

